### ISSUE TITLE
Failed initial build breaks npm watch

### ISSUE THREAD

**Issue by jkinkead** [allenai/syrup#31]
If the first build executed during an `npm watch` fails, the watch never starts, and npm exits.

This should act the same as a build failure while watching, and retry on file change.

The error shown is also much messier than normal:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parse Error: Line 10: Unexpected token =
    at throwError (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2808:21)
    at throwUnexpected (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2870:9)
    at expect (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2879:13)
    at parseObjectInitialiser (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3419:17)
    at parsePrimaryExpression (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3553:20)
    at parseLeftHandSideExpressionAllowCall (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3656:61)
    at parsePostfixExpression (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3696:20)
    at parseUnaryExpression (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3763:16)
    at parseBinaryExpression (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3853:16)
    at parseConditionalExpression (/Users/jkinkead/work/aristo/tables/webapp/node_modules/syrup/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3913:16)
```

**Comment by codeviking** [comment]
@jkinkead So, this is actually working for me.   Let's debug this in person!
